"""
Core Decision Engine
Orchestrates AI (Gemini) evaluation with fallback to domain-specific rule modules.
"""
from __future__ import annotations
from typing import Literal
from engine.career_rules import evaluate_career_option, CAREER_WEIGHTS
from engine.education_rules import evaluate_education_option, EDUCATION_WEIGHTS
from engine.finance_rules import evaluate_finance_option, FINANCE_WEIGHTS
from engine.lifestyle_rules import evaluate_lifestyle_option, LIFESTYLE_WEIGHTS
from engine.ai_engine import validate_options, evaluate_options_with_ai

GOAL_MAP = {
    "career": (evaluate_career_option, CAREER_WEIGHTS),
    "education": (evaluate_education_option, EDUCATION_WEIGHTS),
    "finance": (evaluate_finance_option, FINANCE_WEIGHTS),
    "lifestyle": (evaluate_lifestyle_option, LIFESTYLE_WEIGHTS),
}


def _compute_weighted_score(dimension_scores: dict, weights: dict) -> float:
    total = 0.0
    weight_sum = sum(weights.values())
    for dim, weight in weights.items():
        total += dimension_scores.get(dim, 0.5) * (weight / weight_sum)
    return round(total, 4)


def _compute_confidence(score: float, pros: list, cons: list) -> float:
    """Confidence is the score attenuated by the pros/cons balance."""
    balance = len(pros) / max(len(pros) + len(cons), 1)
    confidence = score * 0.7 + balance * 0.3
    return round(min(confidence, 1.0), 4)


def run_decision_engine(
    goal: Literal["career", "education", "finance", "lifestyle"],
    options: list[str],
    budget: float,
    risk_tolerance: Literal["low", "medium", "high"],
    time_months: int,
    priorities: list[str],
    context: dict = {},
) -> list[dict]:
    """
    Main entry point.
    1. Validates inputs via Gemini (raises ValueError on nonsensical input).
    2. Evaluates options using Gemini AI (primary path).
    3. Falls back to rule-based engine if AI is unavailable.

    Returns a ranked list of decision paths, each with:
      - option: str
      - score: float (0-1)
      - confidence: float (0-1)
      - rank: int
      - pros: list[str]
      - cons: list[str]
      - dimension_scores: dict
      - explanation: str
    """
    if goal not in GOAL_MAP:
        raise ValueError(f"Unknown goal: {goal}. Must be one of {list(GOAL_MAP.keys())}")

    cleaned_options = [o.strip() for o in options if o.strip()]

    # ── Step 1: Validate inputs via AI ───────────────────────────────────────
    validate_options(goal, cleaned_options)  # raises ValueError if nonsensical

    # ── Step 2: Try AI evaluation (Gemini) ───────────────────────────────────
    try:
        results = evaluate_options_with_ai(
            goal=goal,
            options=cleaned_options,
            budget=budget,
            risk_tolerance=risk_tolerance,
            time_months=time_months,
            priorities=priorities,
            context=context,
        )
    except Exception as ai_error:
        # ── Step 3: Fallback to rule-based engine ─────────────────────────────
        print(f"[WARN] AI engine failed ({ai_error}), falling back to rule-based engine.")
        evaluate_fn, weights = GOAL_MAP[goal]
        results = []
        for option in cleaned_options:
            raw = evaluate_fn(option, budget, risk_tolerance, time_months, priorities, context)
            score = _compute_weighted_score(raw["dimension_scores"], weights)
            confidence = _compute_confidence(score, raw["pros"], raw["cons"])
            results.append({
                "option": option,
                "score": score,
                "score_pct": round(score * 100, 1),
                "confidence": confidence,
                "confidence_pct": round(confidence * 100, 1),
                "pros": raw["pros"],
                "cons": raw["cons"],
                "dimension_scores": {k: round(v * 100, 1) for k, v in raw["dimension_scores"].items()},
                "explanation": raw["explanation"] + " [Note: Generated by rule-based fallback engine]",
            })

    # ── Rank by score descending ──────────────────────────────────────────────
    results.sort(key=lambda x: x["score"], reverse=True)
    for i, r in enumerate(results):
        r["rank"] = i + 1

    return results
